const cases={
"uncapped":async(p,click,select,check)=>{await select('pulse-amount','0.7');await select('pulse-spacing','12');await check('train-show-uncapped',true);const r=await p.locator('#train-uncapped-curve').getAttribute('points');A.equal(r.split(' ').length,121);const y=Number(r.split(' ')[12].split(',')[1]);const vals=[.7];for(let i=1;i<=120;i++)vals.push(.98*vals[i-1]+(i%12===0?.7:0));const max=Math.max(1,...vals),raw=vals[12];A.ok(Math.abs(y-(144-128*raw/max))<.0006);A.ok(Number(await p.locator('#train-uncapped-plot').getAttribute('data-max'))===max);A.equal(await p.locator('#train-curve').getAttribute('points').then(s=>s.split(' ')[12].split(',')[1]),'16.000');},
"alternatepulse":async(p,click,select,check)=>{await select('pulse-amount','0.7');await select('pulse-spacing','12');await select('pulse-count','2');await select('pulse-pattern','half');const s=await p.locator('#train-curve').getAttribute('points');const yy=s.split(' ').map(v=>Number(v.split(',')[1]));const a=.7,after12=Math.min(1,a*.98**12+.35),after24=Math.min(1,after12*.98**12+.7);A.ok(Math.abs(yy[12]-(144-128*after12))<.0006);A.ok(Math.abs(yy[24]-(144-128*after24))<.0006);await click('keep-light');await select('pulse-pattern','equal');await click('return-light');A.equal(await p.locator('#pulse-pattern').inputValue(),'half');},
"keptcurve":async(p,click,select,check)=>{await click('keep-light');await select('retention','0.9');await check('light-show-kept-curve',true);A.notEqual(await p.locator('#kept-flash-curve').getAttribute('points'),await p.locator('#flash-curve').getAttribute('points'));A.equal((await p.locator('#kept-flash-curve').getAttribute('points')).split(' ').length,121);await click('return-light');A.equal(await p.locator('#kept-flash-curve').getAttribute('points'),await p.locator('#flash-curve').getAttribute('points'));await click('forget-light');A.ok(await p.locator('#light-show-kept-curve').isDisabled());A.ok(!(await p.locator('#light-show-kept-curve').isChecked()));}
};
const messages={"uncapped": "an uncapped reference shows extra light without changing the capped train", "alternatepulse": "alternating pulse sizes change additions rather than the decay rate", "keptcurve": "kept light curves share the current update axis without changing the lamp"};
const A=require('node:assert/strict'),{chromium}=require('playwright-core');const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={buffers:[],starts:0,stops:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(ch,n,r){const a=new Float32Array(n);const b={length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)};__audio.buffers.push(b);return b}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){__audio.stops++},loop:false}}}window.AudioContext=C;window.webkitAudioContext=C};
(async()=>{A.ok(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});for(const width of[390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(String(e)));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(100);const reveal=async l=>{const ds=await l.evaluate(e=>{let a=[];for(let x=e.parentElement;x;x=x.parentElement)if(x.tagName==='DETAILS'&&!x.open)a.unshift(x.id);return a});for(const d of ds){const s=p.locator('#'+d+'>summary');await s.scrollIntoViewIfNeeded();await s.click()}};const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A.ok(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}));await l.click();await p.waitForTimeout(60)};const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(60)};const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(60)};await cases[mode](p,click,select,check);A.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));A.deepEqual(errors,[]);await p.screenshot({path:`/tmp/pm-${mode}-${width}.png`,fullPage:true});await p.close()}await b.close();console.log(messages[mode])})().catch(e=>{console.error(e);process.exit(1)});
