const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={starts:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(c,n,r){const a=new Float32Array(n);return{length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)}}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){}}}}window.AudioContext=C;window.webkitAudioContext=C};
const cases={
"gapdrawer":async(p,click,select,check)=>{const d=p.locator('#flash-gap-question');A.equal(await d.evaluate(e=>e.open),false);for(const id of ['seek-flash-gap','flash-gap-info','flash-gap-help'])A.equal(await p.locator('#'+id).evaluate(e=>e.closest('details').id),'flash-gap-question');A(await p.locator('#second-glow').evaluate(e=>e.checkVisibility()));await click('seek-flash-gap');A.equal(await p.locator('#frame').inputValue(),'19');const q=d.locator(':scope>summary');await q.scrollIntoViewIfNeeded();await q.focus();await p.keyboard.press('Space');A.equal(await d.evaluate(e=>e.open),false);A(await p.locator('#second-glow').evaluate(e=>e.checkVisibility()));},
"swapflash":async(p,click,select,check)=>{await click('keep-light');await click('swap-flash-retentions');A.equal(await p.locator('#retention').inputValue(),'0.9');A.equal(await p.locator('#retention-b').inputValue(),'0.98');A.equal(await p.locator('#frame').inputValue(),'0');A.equal(await p.locator('#flash-gap-info').innerText(),'Largest flash gap in this strip: 54.61 percentage points at update 19.');await click('return-light');A.equal(await p.locator('#retention').inputValue(),'0.98');await select('retention-b','0.98');A(await p.locator('#swap-flash-retentions').isDisabled());}
};
const messages={"gapdrawer": "the greatest-gap question folds without hiding either working flash", "swapflash": "swapping the two retentions changes both flashes but preserves the kept experiment"};

(async()=>{A(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(120);
const reveal=async l=>{const ids=await l.evaluate(e=>{let a=[];for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){A(id);await p.locator('#'+id+'>summary').scrollIntoViewIfNeeded();await p.locator('#'+id+'>summary').click()}};
const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A(await l.isEnabled(),id+' enabled');A(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),id+' hit');await l.click();await p.waitForTimeout(70)};
const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(70)};
const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(70)};
await cases[mode](p,click,select,check);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/planner-oct9-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
